"""Add user

Revision ID: 79e882a60eb9
Revises: 91b9d7039740
Create Date: 2020-10-07 14:43:58.171963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e882a60eb9'
down_revision = '91b9d7039740'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=280), nullable=True),
    sa.Column('email', sa.String(length=280), nullable=True),
    sa.Column('api_key', sa.String(length=280), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
